name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: your_db_name
          POSTGRES_USER: your_db_user
          POSTGRES_PASSWORD: your_db_password
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Django dependencies
      run: |
        cd services/auth
        pip install -r requirements.txt

    - name: Run Django Tests
      run: |
        cd services/auth
        python manage.py migrate
        python manage.py test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Next.js dependencies
      run: |
        cd services/frontend
        npm install

    - name: Run Next.js Tests
      run: npm run test

