name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ps_db_name
          POSTGRES_USER: ps_db_user
          POSTGRES_PASSWORD: ps_db_password123456
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ps_db_name"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker-compose build

      - name: Run services
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: ./scripts/wait-for-it.sh postgres:5432 --timeout=60 --strict -- echo "Postgres is up"

      - name: Run tests
        run: docker-compose exec app python backend/manage.py test



  frontend:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Next.js dependencies
        run: |
          cd frontend
          npm install

      - name: Run lint
        run: |
          cd frontend
          npm run lint

      - name: Build project
        run: |
          cd frontend
          npm run build

      # - name: Run tests
      #   run: |
      #     cd frontend
      #     npm test

    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: nextjs-build
    #     path: .next

#Testing: For Django : pytest or Django’s built-in test framework. For Next.js : jest.
#to keep in mind : Matrix builds, parallel jobs, and caching.
