name: Notify Discord on CI Completion

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          STATUS="${{ github.event.workflow_run.conclusion }}"
          ACTOR="${{ github.event.workflow_run.actor.login }}"
          COMMIT_MESSAGE=$(echo "${{ github.event.workflow_run.head_commit.message }}" | jq -R .)

          if [ "$STATUS" == "success" ]; then
            STATUS_EMOJI="✅"
          elif [ "$STATUS" == "failure" ]; then
            STATUS_EMOJI="❌"
          else
            STATUS_EMOJI="⚠️"
          fi

          JSON_PAYLOAD=$(jq -n \
            --arg status "**Status**: $STATUS_EMOJI **\($STATUS)**" \
            --arg actor "**Triggered by**: \`$ACTOR\`" \
            --arg commit_message "**Commit Message**: \`$COMMIT_MESSAGE\`" \
            '{
              content: (
                "**CI Pipeline Notification**\n\n" +
                $status + "\n" +
                $actor + "\n" +
                $commit_message
              )
            }')
          
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" \
          $DISCORD_WEBHOOK_URL
