name: Notify Discord on CI Completion

on:
  workflow_run:
    workflows: ["CI"]  # Replace with your CI workflow name
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI Authentication
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Gather Workflow Job Statuses
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          JOBS=$(gh run view ${{ github.event.workflow_run.id }} --json jobs --jq '.jobs[] | "**Job**: \(.name)\n**Status**: \(.conclusion)\n"')
          echo "jobs_status=$JOBS" >> $GITHUB_ENV

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          JOBS_STATUS: ${{ env.jobs_status }}
        run: |
          STATUS="${{ github.event.workflow_run.conclusion }}"
          ACTOR="${{ github.event.workflow_run.actor.login }}"
          COMMIT_MESSAGE=$(echo "${{ github.event.workflow_run.head_commit.message }}" | jq -R .)

          if [ "$STATUS" == "success" ]; then
            STATUS_EMOJI="✅"
          elif [ "$STATUS" == "failure" ]; then
            STATUS_EMOJI="❌"
          else
            STATUS_EMOJI="⚠️"
          fi

          JSON_PAYLOAD=$(jq -n \
            --arg status "**Status**: $STATUS_EMOJI **\($STATUS)**" \
            --arg actor "**Triggered by**: \`$ACTOR\`" \
            --arg commit_message "**Commit Message**: \`$COMMIT_MESSAGE\`" \
            --arg jobs_status "$JOBS_STATUS" \
            '{
              content: (
                "**CI Pipeline Notification**\n\n" +
                $status + "\n" +
                $actor + "\n" +
                $commit_message + "\n\n" +
                "**Job Statuses:**\n" + $jobs_status
              )
            }')
          
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" \
          $DISCORD_WEBHOOK_URL
