name: Notify Discord on CI Completion

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Gather Workflow Job Statuses
        id: gather_statuses
        run: |
          JOBS_STATUS=$(echo "${{ toJSON(github.event.workflow_run.jobs) }}" | jq -r '.[] | "**Job**: \(.name)\n**Status**: \(.conclusion)\n"')
          echo "jobs_status=$JOBS_STATUS" >> $GITHUB_ENV

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          JOBS_STATUS: ${{ env.jobs_status }}
        run: |
          STATUS="${{ github.event.workflow_run.conclusion }}"
          COMMIT_MESSAGE=$(echo "${{ github.event.workflow_run.head_commit.message }}" | jq -R .)

          if [ "$STATUS" == "success" ]; then
            STATUS_EMOJI="✅"
          elif [ "$STATUS" == "failure" ]; then
            STATUS_EMOJI="❌"
          else
            STATUS_EMOJI="⚠️"
          fi

          JSON_PAYLOAD=$(jq -n \
            --arg status "**Status**: $STATUS_EMOJI **\($STATUS)**" \
            --arg commit_message "**Commit Message**: \`$COMMIT_MESSAGE\`" \
            --arg jobs_status "$JOBS_STATUS" \
            '{
              content: (
                "**CI Pipeline Notification**\n\n" +
                $status + "\n" +
                $commit_message + "\n\n" +
                "**Job Statuses:**\n" + $jobs_status
              )
            }')
          
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" \
          $DISCORD_WEBHOOK_URL
