name: Notify Discord on CI Completion

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Workflow Information
        run: |
          echo "Workflow Status: ${{ github.event.workflow_run.conclusion }}"
          echo "Triggered by: ${{ github.event.workflow_run.event }}"
          echo "Actor: ${{ github.event.workflow_run.actor.login }}"
          echo "Commit Message: ${{ github.event.workflow_run.head_commit.message }}"

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          STATUS: ${{ github.event.workflow_run.conclusion }}
          ACTOR: ${{ github.event.workflow_run.actor.login }}
          COMMIT_MESSAGE: ${{ github.event.workflow_run.head_commit.message }}
        run: |
          STATUS_MESSAGE=$(echo "$COMMIT_MESSAGE" | jq -R .)
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"CI Pipeline completed with status: **$STATUS**\nTriggered by: $ACTOR\nCommit message: $STATUS_MESSAGE\"}" \
          $DISCORD_WEBHOOK_URL
